### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by zjin-lcf** [imtsuki/fjsp-gpu#1]
Can you please add a license ?

Thanks

**Comment by imtsuki** [comment]
Added the MIT license

**Comment by zjin-lcf** [comment]
Though I am not familiar with JSP, I found that the best scores are not the same in the CUDA version using the default test sample. However, the score is constant in the CPU version. I suppose there are some races. Do you have some ideas ?  Thanks. 
./main_cuda
...
...
./main_cuda

**Comment by imtsuki** [comment]
In the CPU version I did not invoke `srand()` to set the initial seed, so I think the result is supposed to be deterministic. This is not the case in the CUDA version in which `curand_init()` is called.

**Comment by imtsuki** [comment]
PS: FYI the genetic algorithm used in this repo is highly dependent on random states, e.g. random selections and permutations in each round, so it is unlikely to see the same results between each run.

**Comment by zjin-lcf** [comment]
Thank you for your reply. I replaced the CUDA random function calls with a deterministic random number generation for the states. Please see the link to the file below. 
Running the program multiple times show that the score is still not constant for mk01.fjs. I appreciate your answer when you know the cause.

https://github.com/zjin-lcf/HeCBench/blob/master/fjsp-cuda/main.cu
